# Generated by Django 3.2.13 on 2022-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='direccion',
            field=models.CharField(max_length=240, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
